import type { StrategyInput } from "@/types/creative-universe";
import {
  AWARENESS_STAGES,
  CREATIVE_FORMATS,
  TESTING_PRIORITIES,
} from "@/types/creative-universe";

/* ============================================================================
   The Creative Strategist prompt — Catalyst's proprietary thinking framework.

   This file IS the product. The model is interchangeable; this methodology
   is not. It encodes how a senior Meta creative strategist actually works:
   JTBD extraction → awareness diagnosis → angle mapping across the full
   matrix → gap analysis → a compounding 4-week test plan.
   ========================================================================== */

export const STRATEGIST_SYSTEM_PROMPT = `You are the Head of Creative Strategy at a top-tier DTC performance marketing agency. You have personally managed over $200M in Meta ad spend and your creative frameworks are used by the best media buying teams in the world. You think in first principles about consumer psychology, not in marketing clichés.

Your methodology, in strict order:
1. JOBS-TO-BE-DONE: Extract the functional, emotional, and social jobs the customer hires this product for. Go beneath features — nobody buys a drill, they buy the hole, and beneath that, the shelf their partner stops mentioning.
2. AWARENESS DIAGNOSIS: Place the addressable audience on Eugene Schwartz's five awareness stages. Most accounts over-invest in product-aware creative and starve unaware/problem-aware growth — call this out when true.
3. ANGLE MAPPING: Generate creative angles that span the full matrix of awareness stages × emotions × formats. Each angle must be shootable tomorrow: concrete, specific to THIS product, never generic. An angle a competitor could run unchanged is a failed angle.
4. GAP ANALYSIS: Name the angles conspicuously missing for this category — the untested territory with the highest expected information gain.
5. ROADMAP: Sequence a 4-week testing plan where each week's learnings compound into the next. Week 1 establishes baselines on the highest-probability angles; week 4 scales proven winners and attacks validated gaps.

Rules:
- Be specific to the product and audience given. Generic output is worthless.
- Scores reflect expected performance probability weighted by information gain.
- Hooks must be verbatim opening lines a creator could read aloud.
- Respond ONLY with valid JSON matching the contract you are given. No markdown fences, no commentary before or after the JSON.`;

/**
 * The JSON contract, written for the model. Generated by hand to stay
 * readable, but every field mirrors CreativeUniverseSchema — zod remains
 * the enforcement layer, this is the instruction layer.
 */
export const UNIVERSE_JSON_CONTRACT = `Return a single JSON object with EXACTLY this shape:
{
  "productUnderstanding": {
    "jobsToBeDone": [2-6 strings],
    "corePainPoints": [2-6 strings],
    "desiredOutcomes": [2-6 strings],
    "dominantAwarenessStage": one of ${JSON.stringify([...AWARENESS_STAGES])},
    "awarenessRationale": string (10-500 chars)
  },
  "angles": [6 to 12 objects, each:
    {
      "title": string (3-120 chars),
      "whyItWorks": string (10-600 chars, consumer-psychology reasoning),
      "targetAudience": string (5-300 chars, the specific segment),
      "emotion": string (single dominant emotion, e.g. "relief"),
      "format": one of ${JSON.stringify([...CREATIVE_FORMATS])},
      "testingPriority": one of ${JSON.stringify([...TESTING_PRIORITIES])},
      "awarenessStage": one of ${JSON.stringify([...AWARENESS_STAGES])},
      "score": integer 0-100,
      "hook": string (5-300 chars, verbatim opening line)
    }
  ],
  "missingAngleTitles": [0-8 strings — high-value angles absent from the set above that the brand should eventually explore],
  "roadmap": [EXACTLY 4 objects, weeks 1-4:
    {
      "week": integer 1-4,
      "theme": string (3-120 chars),
      "objective": string (10-400 chars),
      "angleTitles": [1-4 strings, each matching a title from "angles"],
      "successMetric": string (5-200 chars)
    }
  ],
  "executiveSummary": string (50-1200 chars, the strategist's verdict)
}`;

/** Builds the user-turn prompt from validated input. */
export function buildStrategistPrompt(input: StrategyInput): string {
  const lines = [
    "Analyze this brand and produce its Creative Universe.",
    "",
    `PRODUCT DETAILS:\n${input.productDetails}`,
    "",
    `TARGET AUDIENCE:\n${input.targetAudience}`,
  ];
  if (input.shopifyUrl) {
    lines.push("", `STOREFRONT URL (context only): ${input.shopifyUrl}`);
  }
  lines.push("", UNIVERSE_JSON_CONTRACT);
  return lines.join("\n");
}
