-- ============================================================================
-- Catalyst · 0001 — analyses table
-- Run once in the Supabase SQL editor (or `supabase db push`).
--
-- Security model: RLS is ENABLED with NO policies — the table is invisible
-- to anon/authenticated clients. Only the server (service_role key, which
-- bypasses RLS) reads and writes. When user accounts arrive, per-user
-- policies get added here in a later migration.
-- ============================================================================

create table if not exists public.catalyst_analyses (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),

  -- Input snapshot (exactly what the customer submitted)
  shopify_url text,
  product_details text not null,
  target_audience text not null,

  -- The generated Creative Universe (validated against the zod schema
  -- server-side before insert — this column never holds an invalid shape)
  universe jsonb not null,

  -- Engine telemetry for quality monitoring
  provider text not null default 'gemini',
  model text,
  generation_ms integer
);

comment on table public.catalyst_analyses is
  'Every Creative Universe generated by the Catalyst engine, with input snapshot and telemetry.';

-- Lock it down: RLS on, zero client policies. service_role bypasses RLS.
alter table public.catalyst_analyses enable row level security;

-- Query patterns: recency feeds and per-store lookups.
create index if not exists catalyst_analyses_created_at_idx
  on public.catalyst_analyses (created_at desc);
create index if not exists catalyst_analyses_shopify_url_idx
  on public.catalyst_analyses (shopify_url)
  where shopify_url is not null;
